name: Build and Test

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install -y libraylib-dev

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install raylib

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install raylib
          echo "Using pre-installed Raylib"

      - name: Build Game
        run: make

      - name: Run Tests (if applicable)
        run: ./game || echo "Skipping execution on Windows"
